### ISSUE TITLE
PUT returns `Bad Gateway`

### ISSUE THREAD

**Issue by yariplus** [NodeBB/nodebb-package-manager#17]
Any Put request, e.g.

curl -X PUT https://packages.nodebb.org/api/v1/plugins/nodebb-plugin-featured-topics-extended
curl -X PUT https://packages.nodebb.org/api/v1/plugins/nodebb-plugin-camo
etc..

Probably crashing. NPM api change maybe.

**Comment by yariplus** [comment]
False alarm. NPM registry was down. Maybe there should be a check for this?

**Comment by julianlam** [comment]
Thanks, glad to know it wasn't my fault :smile:
