### ISSUE TITLE
svg > png

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-package-manager#18]
Just a small thing I noticed, the png shield.io badge doesn't really use a high resolution and is blurry on screens with higher resolution.
I'd recommend using .svg badges instead, switching the file extension is already sufficient.

**Comment by julianlam** [comment]
@RoiEXLab Better late than never :smile:

**Comment by RoiEXLab** [comment]
Completely forgot about this one tbh :D

**Comment by psychobunny** [comment]
me too, thanks @julianlam 👍
