### ISSUE TITLE
imgur version not updated

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-package-manager#23]
Latest is 2.0.4 https://www.npmjs.com/package/nodebb-plugin-imgur
Here https://packages.nodebb.org/api/v1/plugins/nodebb-plugin-imgur it shows up us 2.0.2.

This is causing test failures in https://travis-ci.org/github/NodeBB/NodeBB/jobs/724371247

**Comment by julianlam** [comment]
Looks to be a transient issue, as that URL reports 2.0.4 now.

Reverted the hardcoded `latest` bypass to confirm.

https://travis-ci.org/github/NodeBB/NodeBB/builds/725288447

**Comment by julianlam** [comment]
https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-imgur&version=1.15.0

```
{"package":"nodebb-plugin-imgur","version":"2.0.4","code":"match-found","message":"The plugin author suggests that you install v2.0.4 for your copy of NodeBB v1.15.0"}
```

**Comment by julianlam** [comment]
Tests passing
