### ISSUE TITLE
I can’t search for my plugin nodebb-plugin-newyear-niuniu in 1.13.0

### ISSUE THREAD

**Issue by AviorAlong** [NodeBB/nodebb-package-manager#24]
I can’t search for my plugin nodebb-plugin-newyear-niuniu in 1.13.0, because I can’t use https://api.github.com/repos/nodebb/nodebb/tags?per_page=100000 to get nodeBB less than 1.13 .4 tags

![image](https://user-images.githubusercontent.com/18592408/108987034-c88d2a80-76cd-11eb-883b-5578832b8992.png)

**Comment by AviorAlong** [comment]
> I can’t search for my plugin nodebb-plugin-newyear-niuniu in 1.13.0, because I can’t use https://api.github.com/repos/nodebb/nodebb/tags?per_page=100000 to get nodeBB less than 1.13 .4 tags
> 
> ![image](https://user-images.githubusercontent.com/18592408/108987034-c88d2a80-76cd-11eb-883b-5578832b8992.png)

I got the 1.13.0 version of nodebb through the "page" parameter, can you fix this problem as soon as possible

![image](https://user-images.githubusercontent.com/18592408/108988573-967cc800-76cf-11eb-9462-4581a6b59629.png)

**Comment by julianlam** [comment]
Looks like this is a NodeBB bug, can you repost there please?
